"""add inventory fields and rich audit logs

Revision ID: 8d01a0b34b45
Revises: 
Create Date: 2026-07-02 11:16:13.778744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d01a0b34b45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('old_quantity', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('change_amount', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('new_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'new_quantity')
    op.drop_column('audit_logs', 'change_amount')
    op.drop_column('audit_logs', 'old_quantity')
    # ### end Alembic commands ###
